version: '3.8'

services:
  client:
    build:
      context: ./apps/client
      dockerfile: Dockerfile
    container_name: tennis-client-container
    image: tennis-client-image
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    ports: 
      - '3000:3000'
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: tennis-api-container
    image: tennis-api-image
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    ports: 
      - '8081:8081' 
  model-api:
    build:
      context: ./apps/modelApi
      dockerfile: Dockerfile
    container_name: tennis-model-api-container
    image: tennis-model-api-image
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    ports: 
      - '8082:8082' 

networks:
  app-network:
    driver: bridge